on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Verify
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
    env:
      CI: 1
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: make go-mod
      - name: Test
        run: make test
      - name: Lint
        run: make lint
